<template>
  <div class="bg-gray-100 h-full p-4">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex items-center justify-center py-8 flex-col gap-4">
        <h1 class="text-gray-900 text-4xl font-serif text-center">
          Mild Chaos Ideas
        </h1>
        <p class="text-gray-700 text-sm text-center max-w-md">
          A collection of ideas for mild chaos in daily life. Generated by AI,
          reviewed by a human.
        </p>
        <div class="mt-4 flex gap-4 justify-between w-full items-center">
          <div class="flex gap-4">
            <div class="flex flex-col gap-2">
              <Select v-model="sortBy">
                <SelectTrigger class="w-40">
                  <SelectValue placeholder="Sort by" />
                </SelectTrigger>
                <SelectContent>
                  <SelectGroup>
                    <SelectItem value="votes"> 👍 Votes </SelectItem>
                    <SelectItem value="timestamp"> ⏱️ Newest </SelectItem>
                  </SelectGroup>
                </SelectContent>
              </Select>
            </div>

            <div class="flex flex-col gap-2">
              <Select v-model="selectedCategory">
                <SelectTrigger class="w-48">
                  <SelectValue placeholder="Filter by category" />
                </SelectTrigger>
                <SelectContent>
                  <SelectGroup>
                    <SelectItem value="all">All Categories</SelectItem>
                    <SelectItem
                      v-for="category in categories"
                      :key="category"
                      :value="category"
                    >
                      {{ formatCategory(category) }}
                    </SelectItem>
                  </SelectGroup>
                </SelectContent>
              </Select>
            </div>

            <div class="flex flex-col gap-2">
              <Select v-model="selectedSource">
                <SelectTrigger class="w-40">
                  <SelectValue placeholder="Filter by source" />
                </SelectTrigger>
                <SelectContent>
                  <SelectGroup>
                    <SelectItem value="all">All Sources</SelectItem>
                    <SelectItem value="ai">AI Generated</SelectItem>
                    <SelectItem value="human">Human Created</SelectItem>
                  </SelectGroup>
                </SelectContent>
              </Select>
            </div>
          </div>

          <div class="flex flex-col gap-2">
            <Button variant="default" @click="showSubmitDialog = true">
              Submit Idea
            </Button>
          </div>
        </div>
      </div>
      <div
        class="grid grid-cols-1 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-2 xl:grid-cols-3 gap-6 justify-items-center"
      >
        <IdeaCard
          v-for="idea in filteredAndSortedIdeas"
          :key="idea.id"
          :idea="idea"
          @vote="updateVotes"
        />
      </div>

      <Dialog :open="showSubmitDialog" @update:open="showSubmitDialog = false">
        <DialogContent class="sm:max-w-[425px]">
          <DialogHeader>
            <DialogTitle>Submit a New Idea</DialogTitle>
            <DialogDescription>
              Share your mild chaos idea with the community.
            </DialogDescription>
          </DialogHeader>
          <div class="grid gap-4 py-4">
            <div class="grid gap-2">
              <Label for="title">Title</Label>
              <Input
                id="title"
                v-model="newIdea.title"
                placeholder="Enter a catchy title"
              />
            </div>
            <div class="grid gap-2">
              <Label for="description">Description</Label>
              <Textarea
                id="description"
                v-model="newIdea.description"
                placeholder="Describe your idea..."
              />
            </div>
            <div class="grid gap-2">
              <Label for="category">Category</Label>
              <Select v-model="newIdea.category">
                <SelectTrigger>
                  <SelectValue placeholder="Select a category" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem
                    v-for="category in categories"
                    :key="category"
                    :value="category"
                  >
                    {{ formatCategory(category) }}
                  </SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" @click="showSubmitDialog = false">
              Cancel
            </Button>
            <Button type="submit" @click="submitIdea">Submit</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import IdeaCard from '@/components/IdeaCard.vue'
import {
  Select,
  SelectTrigger,
  SelectContent,
  SelectItem,
  SelectValue,
} from '@/components/ui/select'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Label } from '@/components/ui/label'

import { useToast } from '@/components/ui/toast/use-toast'

interface Idea {
  id: string
  title: string
  description: string
  category: string
  timestamp: number
  votes: { up: number; down: number }
  isAiGenerated: boolean
}

const categories = [
  'home_decoration',
  'office_prank',
  'time_manipulation',
  'home_organization',
  'kitchen',
  'communication',
  'organization',
]

const ideas = ref<Idea[]>([
  {
    id: 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
    title: 'Rotate Family Photos',
    description:
      'Rotate all the family photos on the wall slightly to the left.',
    category: 'home_decoration',
    timestamp: Date.now(),
    votes: { up: 0, down: 0 },
    isAiGenerated: true,
  },
  {
    id: '7e9d5eb7-8c44-4f1a-9aa1-b01e90b12345',
    title: 'Adjust House Clocks',
    description:
      "Set all the clocks in your house to be 7 minutes fast. Don't tell anyone.",
    category: 'time_manipulation',
    timestamp: Date.now(),
    votes: { up: 0, down: 0 },
    isAiGenerated: true,
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440000',
    title: 'Stapler Swap',
    description:
      "Swap your coworker's stapler with yours (bonus if they're identical).",
    category: 'office_prank',
    timestamp: Date.now(),
    votes: { up: 0, down: 0 },
    isAiGenerated: true,
  },
  {
    id: '6ba7b810-9dad-11d1-80b4-00c04fd430c8',
    title: 'Shoe Direction Change',
    description:
      'Turn one shoe of each pair in your shoe rack to face the wrong direction.',
    category: 'home_organization',
    timestamp: Date.now(),
    votes: { up: 0, down: 0 },
    isAiGenerated: true,
  },
  {
    id: '6ba7b811-9dad-11d1-80b4-00c04fd430c8',
    title: 'Mysterious Text',
    description:
      'Send someone a text saying, "Nevermind, wrong person." Then don\'t elaborate.',
    category: 'communication',
    timestamp: Date.now(),
    votes: { up: 0, down: 0 },
    isAiGenerated: true,
  },
  {
    id: '6ba7b812-9dad-11d1-80b4-00c04fd430c8',
    title: 'Loose Jar Lids',
    description: 'Slightly loosen the lids on all the jars in the fridge.',
    category: 'kitchen',
    timestamp: Date.now(),
    votes: { up: 0, down: 0 },
    isAiGenerated: true,
  },
  {
    id: '6ba7b813-9dad-11d1-80b4-00c04fd430c8',
    title: 'Cereal Storage Swap',
    description:
      'Put the cereal box where the bowls go and the bowls where the cereal goes.',
    category: 'kitchen',
    timestamp: Date.now(),
    votes: { up: 0, down: 0 },
    isAiGenerated: true,
  },
  {
    id: '6ba7b814-9dad-11d1-80b4-00c04fd430c8',
    title: 'Fake Meeting Notice',
    description:
      "Print a fake meeting invitation, stick it on a random colleague's desk, and watch.",
    category: 'office_prank',
    timestamp: Date.now(),
    votes: { up: 0, down: 0 },
    isAiGenerated: true,
  },
  {
    id: '6ba7b815-9dad-11d1-80b4-00c04fd430c8',
    title: 'Mismatched Lightbulb',
    description:
      'Replace one of the lightbulbs in a multi-light fixture with a different color.',
    category: 'home_decoration',
    timestamp: Date.now(),
    votes: { up: 0, down: 0 },
    isAiGenerated: true,
  },
  {
    id: '6ba7b816-9dad-11d1-80b4-00c04fd430c8',
    title: 'Drawer Content Swap',
    description:
      'Randomly swap two drawer contents in your kitchen or workspace.',
    category: 'organization',
    timestamp: Date.now(),
    votes: { up: 0, down: 0 },
    isAiGenerated: true,
  },
  {
    id: '6ba7b817-9dad-11d1-80b4-00c04fd430c8',
    title: 'Keyboard Letter Swap',
    description:
      "Carefully swap two letter keycaps on a colleague's keyboard. M and N are perfect candidates.",
    category: 'office_prank',
    timestamp: Date.now(),
    votes: { up: 0, down: 0 },
    isAiGenerated: true,
  },
  {
    id: '6ba7b818-9dad-11d1-80b4-00c04fd430c8',
    title: 'Reverse Book Order',
    description:
      'Rearrange all books on a shelf to face spine-inward. Watch people try to find their books.',
    category: 'home_organization',
    timestamp: Date.now(),
    votes: { up: 0, down: 0 },
    isAiGenerated: true,
  },
  {
    id: '6ba7b819-9dad-11d1-80b4-00c04fd430c8',
    title: 'Silent Phone Mode',
    description:
      "Change everyone's phone ringtone to silent during lunch break. Deny all involvement.",
    category: 'office_prank',
    timestamp: Date.now(),
    votes: { up: 0, down: 0 },
    isAiGenerated: true,
  },
  {
    id: '6ba7b820-9dad-11d1-80b4-00c04fd430c8',
    title: 'Spice Jar Shuffle',
    description:
      "Switch the contents of the salt and sugar containers. Perfect for April Fools'!",
    category: 'kitchen',
    timestamp: Date.now(),
    votes: { up: 0, down: 0 },
    isAiGenerated: true,
  },
  {
    id: '6ba7b821-9dad-11d1-80b4-00c04fd430c8',
    title: 'Calendar Confusion',
    description:
      'Change all office calendars to show a different month. Watch the meeting chaos unfold.',
    category: 'time_manipulation',
    timestamp: Date.now(),
    votes: { up: 0, down: 0 },
    isAiGenerated: true,
  },
  {
    id: '6ba7b822-9dad-11d1-80b4-00c04fd430c8',
    title: 'Furniture Shift',
    description:
      'Move all furniture in a room exactly 2 inches to the left. See who notices.',
    category: 'home_decoration',
    timestamp: Date.now(),
    votes: { up: 0, down: 0 },
    isAiGenerated: true,
  },
])

const sortBy = ref<'votes' | 'timestamp'>('timestamp')
const selectedCategory = ref<string>('all')
const selectedSource = ref<'all' | 'ai' | 'human'>('all')

const filteredAndSortedIdeas = computed(() => {
  let filtered = ideas.value

  if (selectedCategory.value !== 'all') {
    filtered = filtered.filter(
      (idea) => idea.category === selectedCategory.value
    )
  }

  if (selectedSource.value !== 'all') {
    filtered = filtered.filter((idea) =>
      selectedSource.value === 'ai' ? idea.isAiGenerated : !idea.isAiGenerated
    )
  }

  return filtered.sort((a, b) => {
    if (sortBy.value === 'votes') {
      return b.votes.up - b.votes.down - (a.votes.up - a.votes.down)
    } else {
      return b.timestamp - a.timestamp
    }
  })
})

const formatCategory = (category: string) => {
  return category
    .split('_')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')
}

const updateVotes = (id: string, type: 'up' | 'down') => {
  const idea = ideas.value.find((idea) => idea.id === id)
  if (idea) {
    idea.votes[type] += 1
  }
}

const showSubmitDialog = ref(false)
const { toast } = useToast()

const newIdea = ref({
  title: '',
  description: '',
  category: '',
})

const submitIdea = () => {
  if (
    !newIdea.value.title ||
    !newIdea.value.description ||
    !newIdea.value.category
  ) {
    toast({
      title: 'Error',
      description: 'Please fill in all fields',
      variant: 'destructive',
    })
    return
  }

  const idea: Idea = {
    id: crypto.randomUUID(),
    title: newIdea.value.title,
    description: newIdea.value.description,
    category: newIdea.value.category,
    timestamp: Date.now(),
    votes: { up: 0, down: 0 },
    isAiGenerated: false,
  }

  ideas.value.unshift(idea)
  showSubmitDialog.value = false
  newIdea.value = {
    title: '',
    description: '',
    category: '',
  }

  toast({
    title: 'Success',
    description: 'Your idea has been submitted!',
  })
}
</script>
